### ISSUE TITLE
Qt: Session management error: None of the authentication protocols specified are supported

### ISSUE THREAD

**Issue by Havied** [anak10thn/ignsdk-qt#171]
setelah update ada pemberitahuan 

"Qt: Session management error: None of the authentication protocols specified are supported"

**Comment by anak10thn** [comment]
errornya muncul saat apa om? kronologi dan gambarmestinya bisa di kirim lebih jelas @Havied

**Comment by Havied** [comment]
error itu muncul saat setelah update, dan ketika mau menjalankan program muncul peringatan seperti ini   
![err](https://cloud.githubusercontent.com/assets/6139998/6522208/c88ee9f0-c414-11e4-848b-b737aaa47998.png)

**Comment by anak10thn** [comment]
OSnya apa nih bro? @Havied

**Comment by Havied** [comment]
IGN9.3

**Comment by anak10thn** [comment]
ok akan di cek thanks infonya

**Comment by anak10thn** [comment]
akan di perbaiki di versi package selanjutnya
